### ISSUE TITLE
[feature]update app icon

### ISSUE THREAD

**Issue by iamhrck** [iamhrck/the_roulette_app#7]
# Update App icon

- アプリアイコンをデフォルトのものからオリジナルのものに変更する

**Comment by iamhrck** [comment]
### アイコン作成
[Canva](https://www.canva.com/design/DAF5r2Fcmng/M4iV2QjvhDQlnMfmlUE5kQ/edit?referrer=icons-landing-page)

### デフォルトアイコン変更
flutter_launcher_iconsを追加

```bash
flutter pub add flutter_launcher_icons
```

pubsec.yamlに設定追加

```yaml
flutter_icons:       
  android: true
  ios: true
  image_path: "assets/app_icon.png"
```

コマンドによる生成
```bash
flutter pub run flutter_launcher_icons:main
```

### Androidアプリアイコン調整
Android Studioの`Image Asset`でアイコンサイズを調整

https://washiharu.com/flutter-app-icon-setting/
